# Moodle AI Index

Central index for AI generated documentation.

This file links all indexes generated by moodle-ai.

It allows both humans and AI systems to quickly locate
structural information about the Moodle installation.

---